### ISSUE TITLE
Complexidade do fluxo de controle do programa (McCabe)

### ISSUE THREAD

**Issue by Patriarka** [Patriarka/ck#1]
Como usuário, eu quero uma métrica que apresente a complexidade do fluxo de controle do programa.

**Comment by magsilva** [comment]
O artigo original sobre o McCabe é o [A Complexity Measure, de 1976](https://doi.org/10.1109/TSE.1976.233837). Segue o BibTeX completo do artigo:

@Article{McCabe:1976,
  title    = {A Complexity Measure},
  author   = {Thomas J. McCabe},
  journal          = {Transactions on Software Engineering},
  address          = USA,
  e-issn           = {1939-3520},
  issn             = {0098-5589},
  publisher        = {IEEE Computer Society},
  volume   = {2},
  number   = {4},
  pages    = {308--320},
  month    = dec,
  year     = {1976},
  doi      = {10.1109/TSE.1976.233837},
  abstract = {This paper describes a graph-theoretic complexity measure and illustrates how it can be used to manage and control program complexity. The paper first explains how the graph-theory concepts apply and gives an intuitive explanation of the graph concepts in programming terms. The control graphs of several actual Fortran programs are then presented to illustrate the correlation between intuitive complexity and the graph-theoretic complexity. Several properties of the graph-theoretic complexity are then proved which show, for example, that complexity is independent of physical size (adding or subtracting functional statements leaves complexity unchanged) and complexity depends only on the decision structure of a program.},
  keywords = {testing, Basis, complexity measure, control flow, decomposition, graph theory, independence, linear, modularization, programming, reduction, software},
}

Provavelmente existem descrições suficientemente detalhadas em português nas quais vocês podem se basear. Ao invés de McCabe, às vezes a métrica é conhecida como complexidade ciclomática.
